Controllers/DoctorDepartmentController.cs
using HMS.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data;
using System.Data.SqlClient;

namespace HMS.Controllers
{
    public class DoctorDepartmentController : Controller
    {
        private IConfiguration configuration;

        public DoctorDepartmentController(IConfiguration _configuration)
        {
            configuration = _configuration;
        }

        public IActionResult DoctorDepartmentList()
        {
            string connectionString = configuration.GetConnectionString("ConnectionString");
            using SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();

            SqlCommand command = new SqlCommand("PR_DocDept_DoctorDepartment_SelectAll", connection);
            command.CommandType = CommandType.StoredProcedure;

            SqlDataReader reader = command.ExecuteReader();
            DataTable table = new DataTable();
            table.Load(reader);
            return View(table);
        }
        #region User Drop Down
        public void UserDropDown()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();

                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;
                command.CommandText = "PR_USR_User_SelectForDropDown";

                SqlDataReader reader = command.ExecuteReader();
                DataTable dt = new DataTable();
                dt.Load(reader);

                List<SelectListItem> userList = new List<SelectListItem>();
                foreach (DataRow data in dt.Rows)
                {
                    userList.Add(new SelectListItem
                    {
                        Value = data["UserID"].ToString(),
                        Text = data["UserName"].ToString()
                    });
                }

                ViewBag.UserList = userList;
            }
        }


        #endregion

        #region Doctor Drop Down
        public void DoctorDropDown()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();

                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;
                command.CommandText = "PR_DOC_Doctor_SelectForDropDown";

                SqlDataReader reader = command.ExecuteReader();
                DataTable dt = new DataTable();
                dt.Load(reader);

                List<SelectListItem> doctorList = new List<SelectListItem>();
                foreach (DataRow data in dt.Rows)
                {
                    doctorList.Add(new SelectListItem
                    {
                        Value = data["DoctorID"].ToString(),
                        Text = data["DoctorName"].ToString()
                    });
                }

                ViewBag.DoctorList = doctorList;
            }
        }
        #endregion

        #region Department Drop Down
        public void DepartmentDropDown()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();

                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;
                command.CommandText = "PR_DEPT_Department_SelectForDropDown";

                SqlDataReader reader = command.ExecuteReader();
                DataTable dt = new DataTable();
                dt.Load(reader);

                List<SelectListItem> departmentList = new List<SelectListItem>();
                foreach (DataRow data in dt.Rows)
                {
                    departmentList.Add(new SelectListItem
                    {
                        Value = data["DepartmentID"].ToString(),
                        Text = data["DepartmentName"].ToString()
                    });
                }

                ViewBag.DepartmentList = departmentList;
            }
        }
        #endregion

        public IActionResult DoctorDepartmentDelete(int DoctorDepartmentID)
        {
            try
            {
                string connectionString = configuration.GetConnectionString("ConnectionString");
                using SqlConnection connection = new SqlConnection(connectionString);
                connection.Open();

                SqlCommand command = new SqlCommand("PR_DocDept_DoctorDepartment_Delete", connection);
                command.CommandType = CommandType.StoredProcedure;
                command.Parameters.Add("@DoctorDepartmentID", SqlDbType.Int).Value = DoctorDepartmentID;
                command.ExecuteNonQuery();

                // ✅ Success msg
                TempData["SuccessMessage"] = "Doctor-Department deleted successfully.";
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Error: " + ex.Message;
            }

            return RedirectToAction("DoctorDepartmentList");
        }


        //#region Doctor Department Add Edit
        //[HttpGet]
        //public IActionResult DoctorDepartmentAddEdit()
        //{

        //    return View();
        //}

        //[HttpPost]
        //public IActionResult DoctorDepartmentAddEdit(DoctorDepartmentModelAddEdit DoctorDepartmentModelAddEdit)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        foreach (var error in ModelState.Values.SelectMany(v => v.Errors))
        //        {
        //            Console.WriteLine("Model Error: " + error.ErrorMessage);
        //        }
        //    }

        //    Console.WriteLine(DoctorDepartmentModelAddEdit.DoctorDepartmentID);
        //    Console.WriteLine(DoctorDepartmentModelAddEdit.DoctorID);
        //    Console.WriteLine(DoctorDepartmentModelAddEdit.DepartmentID);
        //    Console.WriteLine(DoctorDepartmentModelAddEdit.Modified);
        //    Console.WriteLine(DoctorDepartmentModelAddEdit.UserID);
        //    if (DoctorDepartmentModelAddEdit.Modified == null)
        //    {
        //        DoctorDepartmentModelAddEdit.Modified = DateTime.Now;
        //    }
        //    Console.WriteLine("Mosified: " + DoctorDepartmentModelAddEdit.Modified);
        //    Console.WriteLine("DoctorDepartmentID", DoctorDepartmentModelAddEdit.DoctorDepartmentID);
        //    Console.WriteLine("DoctorID", DoctorDepartmentModelAddEdit.DoctorID);
        //    Console.WriteLine("DepartmentID", DoctorDepartmentModelAddEdit.DepartmentID);
        //    Console.WriteLine(DoctorDepartmentModelAddEdit.UserID);

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            string connectionString = this.configuration.GetConnectionString("ConnectionString");
        //            using (SqlConnection connection = new SqlConnection(connectionString))
        //            {
        //                connection.Open();
        //                using (SqlCommand command = connection.CreateCommand())
        //                {
        //                    command.CommandType = CommandType.StoredProcedure;
        //                    Console.WriteLine(DoctorDepartmentModelAddEdit.DoctorDepartmentID);
        //                    if (DoctorDepartmentModelAddEdit.DoctorDepartmentID != null && DoctorDepartmentModelAddEdit.DoctorDepartmentID > 0)
        //                    {
        //                        command.CommandText = "PR_DocDept_DoctorDepartment_Update";
        //                        command.Parameters.AddWithValue("@DoctorDepartmentID", DoctorDepartmentModelAddEdit.DoctorDepartmentID);
        //                    }
        //                    else
        //                    {
        //                        command.CommandText = "PR_DocDept_DoctorDepartment_Insert";
        //                    }

        //                    command.Parameters.Add("@DoctorID", SqlDbType.Int).Value = DoctorDepartmentModelAddEdit.DoctorID;
        //                    command.Parameters.Add("@DepartmentID", SqlDbType.Int).Value = DoctorDepartmentModelAddEdit.DepartmentID;
        //                    command.Parameters.Add("@Modified", SqlDbType.DateTime).Value = DoctorDepartmentModelAddEdit.Modified;
        //                    command.Parameters.Add("@UserID", SqlDbType.Int).Value = DoctorDepartmentModelAddEdit.UserID;

        //                    command.ExecuteNonQuery();
        //                }
        //            }
        //            DepartmentDropDown();
        //            return RedirectToAction("DoctorDepartmentList");
        //        }
        //        catch (Exception ex)
        //        {
        //            TempData["ErrorMessage"] = "Error saving Doctor-Department: " + ex.Message;
        //        }
        //    }
        //    DepartmentDropDown()

        //    return View("DoctorDepartmentAddEdit");
        //}
        //#endregion

        //#region Doctor Department Form Fill
        //public IActionResult DoctorDepartmentForm(int ID)
        //{
        //    DoctorDepartmentModelAddEdit model = new DoctorDepartmentModelAddEdit();

        //    if (ID > 0)
        //    {
        //        try
        //        {

Views/DoctorDepartment/DoctorDepartmentAddEdit.cshtml
@* @model HMS.Models.DoctorDepartmentModelAddEdit

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow-sm border-0 rounded-4" style="background-color: #fefefe;">
                <div class="card-header text-center rounded-top-4" style="background-color: #eaf6ff;">
                    <h4 class="mb-0 text-primary">Assign Doctor to Department</h4>
                </div>
                <div class="card-body px-4 py-3" style="background-color: #fcfcfc;">
                    <form method="post" asp-controller="DoctorDepartment" asp-action="DoctorDepartmentAddEdit">

                        <input asp-for="DoctorDepartmentID" type="hidden" />

                        <div class="mb-3">
                            <label for="DoctorID" class="form-label fw-bold text-dark">Doctor ID</label>
                            <input  asp-for="DoctorID" type="number" class="form-control border-light rounded-3" id="DoctorID" name="DoctorID" placeholder="Enter Doctor ID" style="background-color: #f5faff;" required />
                        </div>

                        <div class="mb-3">
                            <label asp-for="DepartmentID" class="form-label fw-bold text-dark">Department ID</label>
                            <input asp-for="DepartmentID" type="number" class="form-control border-light rounded-3" id="DepartmentID" name="DepartmentID" placeholder="Enter Department ID" style="background-color: #f5faff;" required />
                        </div>
                 
                        <input type="hidden" />
                        <input asp-for="Modified" type="hidden" />


                        <div class="col-md-6 mb-3">
                            <label for="UserID" class="form-label fw-bold text-dark">User ID</label>
                            <input asp-for="UserID" type="number" class="form-control border-light rounded-3" id="UserID" name="UserID" placeholder="Enter linked user ID" style="background-color: #f5faff;" required>
                        </div>

                        <!-- ✅ Buttons Section -->
                        <div class="d-flex justify-content-between">
                            <a href="/DoctorDepartment/DoctorDepartmentList" class="btn btn-outline-primary btn-sm rounded-pill px-4 fw-semibold">⬅ Back to DoctorDepartment List</a>
                            <button type="submit" class="btn btn-outline-primary btn-sm rounded-pill px-4 fw-semibold">Submit</button>
                        </div>
                    </form>
                </div>
                <div class="card-footer text-center small text-muted rounded-bottom-4" style="background-color: #eaf6ff;">
                    © HMS System • 2025
                </div>
            </div>
        </div>
    </div>
</div> *@
@model HMS.Models.DoctorDepartmentModelAddEdit

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow-sm border-0 rounded-4" style="background-color: #fefefe;">
                <div class="card-header text-center rounded-top-4" style="background-color: #eaf6ff;">
                    <h4 class="mb-0 text-primary">Assign Doctor to Department</h4>
                </div>
                <div class="card-body px-4 py-3" style="background-color: #fcfcfc;">
                    <form method="post" asp-controller="DoctorDepartment" asp-action="DoctorDepartmentAddEdit">

                        <input asp-for="DoctorDepartmentID" type="hidden" />

                        <!-- ✅ Doctor Dropdown -->
                        <div class="mb-3">
                            <label asp-for="DoctorID" class="form-label fw-bold text-dark">Doctor</label>
                            <select asp-for="DoctorID"
                                    asp-items="ViewBag.DoctorList"
                                    class="form-control border-light rounded-3"
                                    style="background-color: #f5faff;" required>
                                <option value="">-- Select Doctor --</option>
                            </select>
                            <span asp-validation-for="DoctorID" class="text-danger"></span>
                        </div>

                        <!-- ✅ Department Dropdown -->
                        <div class="mb-3">
                            <label asp-for="DepartmentID" class="form-label fw-bold text-dark">Department</label>
                            <select asp-for="DepartmentID"
                                    asp-items="ViewBag.DepartmentList"
                                    class="form-control border-light rounded-3"
                                    style="background-color: #f5faff;" required>
                                <option value="">-- Select Department --</option>
                            </select>
                            <span asp-validation-for="DepartmentID" class="text-danger"></span>
                        </div>

                        <!-- Hidden Modified -->
                        <input asp-for="Modified" type="hidden" />

                        <!-- ✅ User Dropdown -->
                        <div class="mb-3">
                            <label asp-for="UserID" class="form-label fw-bold text-dark">User</label>
                            <select asp-for="UserID"
                                    asp-items="ViewBag.UserList"
                                    class="form-control border-light rounded-3"
                                    style="background-color: #f5faff;" required>
                                <option value="">-- Select User --</option>
                            </select>
                            <span asp-validation-for="UserID" class="text-danger"></span>
                        </div>

                        <!-- ✅ Buttons Section -->
                        <div class="d-flex justify-content-between">
                            <a href="/DoctorDepartment/DoctorDepartmentList" class="btn btn-outline-primary btn-sm rounded-pill px-4 fw-semibold">
                                ⬅ Back to DoctorDepartment List
                            </a>
                            <button type="submit" class="btn btn-outline-primary btn-sm rounded-pill px-4 fw-semibold">
                                Submit
                            </button>
                        </div>
                    </form>
                </div>
                <div class="card-footer text-center small text-muted rounded-bottom-4" style="background-color: #eaf6ff;">
                    © HMS System • 2025
                </div>
            </div>
        </div>
    </div>
</div>

Views/DoctorDepartment/DoctorDepartmentList.cshtml
@model DataTable
@using System.Data

@{
    ViewData["Title"] = "Doctor-Department Mapping List";
}

<!-- SweetAlert2 CDN -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<h1 class="mb-4">Doctor-Department Mapping List</h1>

<!-- Search Form -->
<div>
    <form method="get" asp-action="DepartmentList" class="d-flex">
        <div class="input-group">
            <input type="text" name="searchTerm" class="form-control" placeholder="Search by Department Name" />
            <button type="submit" class="btn btn-outline-primary">Search</button>
        </div>
    </form>
    <br />
</div>
<!-- ✅ Buttons -->
<div class="d-flex justify-content-between mb-3">
    <div>
        <a class="btn btn-success me-2" href="/DoctorDepartment/ExportToCSV">⬇️ Download CSV</a>
        <a class="btn btn-success me-2" href="/DoctorDepartment/ExportToExcel">📂 Download Excel</a>
        <a class="btn btn-primary" href="/DoctorDepartment/DoctorDepartmentAddEdit">➕ Add DoctorDepartment</a> <!-- ✅ Add User button -->
    </div>
    <div>
        <a class="btn btn-secondary me-2" asp-controller="Dashboard" asp-action="Index">🏠 Go to Dashboard</a>
    
        <button type="button" class="btn btn-danger" onclick="confirmDeleteSelected()">🗑 Delete Selected Users</button>
    </div>
</div>

<!-- Error Message -->
@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">@TempData["ErrorMessage"]</div>
}

<!-- DoctorDepartment Table -->
<table class="table table-bordered table-hover shadow-sm">
    <thead class="table-primary">
      
            <tr>
                <th style="min-width: 150px;">DoctorDept ID</th>
            <th style="min-width: 160px;">Actions</th>
                <th style="min-width: 150px;">Doctor Name</th>
                <th style="min-width: 200px;">Department Name</th>
                <th style="min-width: 120px;">Created</th>
                <th style="min-width: 160px;">Modified</th>
                <th style="min-width: 100px;">User ID</th>
                <th style="min-width: 150px;">User Name</th>
                <th style="min-width: 200px;">Email</th>
                <th style="min-width: 140px;">Mobile No</th>
                
            </tr>
        </thead>
        <tbody>
            @foreach (DataRow dr in Model.Rows)
            {
                <tr>
                    <td>@dr["DoctorDepartmentID"]</td>
                <td>
                    <!-- Edit Button -->
                    <a asp-controller="DoctorDepartment"
                       asp-action="DoctorDepartmentForm"
                       asp-route-ID="@dr["DoctorDepartmentID"]"
                       class="btn btn-primary btn-sm me-1">
                        Edit
                    </a>

                    <!-- SweetAlert Delete Button -->
                    <button type="button"
                            class="btn btn-danger btn-sm"
                            onclick="confirmDelete('@dr["DoctorDepartmentID"]', '@dr["Doctorname"]')">
                        Delete
                    </button>
                </td>
                <td>@dr["doctorname"]</td>
                    <td>@dr["deptname"]</td>
                    <td>@Convert.ToDateTime(dr["Created"]).ToString("dd-MM-yyyy")</td>
                    <td>@Convert.ToDateTime(dr["Modified"]).ToString("dd-MM-yyyy")</td>
                    <td>@dr["UserID"]</td>
                    <td>@dr["UserName"]</td>
                    <td>@dr["Email"]</td>
                    <td>@dr["MobileNo"]</td>
                   
                </tr>
            }
        </tbody>
    </table>
</div>

<!-- SweetAlert Delete Script -->
<script>
    function confirmDelete(id, name) {
        Swal.fire({
            title: 'Are you sure?',
            text: `Do you really want to delete the mapping for Doctor "${name}"?`,
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#d33',
            cancelButtonColor: '#6c757d',
            confirmButtonText: 'Yes, delete it!',
            cancelButtonText: 'Cancel'
        }).then((result) => {
            if (result.isConfirmed) {
                window.location.href = `/DoctorDepartment/DoctorDepartmentDelete?DoctorDepartmentID=${id}`;
            }
        });
    }
</script>